version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      microsoft:
        patterns:
          - "Microsoft.*"
      test-tooling:
        patterns:
          - "xunit*"
          - "NSubstitute"
          - "Shouldly"
          - "coverlet.*"
          - "NetArchTest.Rules"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
